name: ridesafe_api
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

# TODO: add core as a dependency here

# dependencies:
#   core: ^1.8.0
#     path: ../ridesafe_core

dependencies:
  ridesafe_core:
    path: D:/dev/ridesafe/ridesafe_core

  ridesafe_cloud_database_impl:
    path: D:/dev/ridesafe/ridesafe_cloud_database_impl

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
